name: Make conda package
on:
  push:
    branches:
      - main
    tags: [ '*' ]

jobs:
  build:
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          conda-remove-defaults: true
          channels: conda-forge
          python-version: "3.12"
          conda-build-version: "26.3.0"

      - name: "Build package"
        run: |
          mkdir conda-bld
          conda build --output-folder conda-bld conda/

      - uses: actions/upload-artifact@v7
        with:
          path: conda-bld/noarch/imgcif_creator*
          archive: false

      - name: publish to anaconda.org
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          conda install -q anaconda-client
          anaconda --token ${{ secrets.ANACONDA_ORG_UPLOAD_TOKEN }} upload \
            --user COMCIFS \
            conda-bld/noarch/imgcif_creator*
