name: Make conda package
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          conda-remove-defaults: true
          channels: conda-forge
          python-version: "3.12"
          conda-build-version: "26.3.0"

      - run: |
          mkdir conda-bld
          conda build --output-folder conda-bld conda/

      - uses: actions/upload-artifact@v4
        with:
          name: conda-package
          path: conda-bld/noarch/imgcif_creator*
